# This is a graphql-config
# https://www.prisma.io/docs/1.7/graphql-ecosystem/graphql-config/overview-quaidah9pi#usage
projects:
  # the full server which is only accessible over auth
  database:
    schemaPath: packages/api/generated/prisma.graphql
    extensions:
      endpoints:
        e2e:
          prisma: database/e2e/prisma.yml
          url: http://localhost:4466/blogr/e2e
        dev:
          prisma: database/dev/prisma.yml
          url: https://eu1.prisma.sh/dominik-ferber-4ba4fb/blogr/dev
  # the api-server itself which the frontend/backend talk to
  app:
    schemaPath: packages/api/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
